name: build and deploy

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**/*.md'
      - '**/*.gitignore'
      - '**/*.gitattributes'
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      nuget_push:
        description: 'Push to nuget?'
        required: false
        default: 'false'

permissions:
  contents: read

env:
  DOTNET_NOLOGO: true                     # Disable the .NET logo
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true # Disable the .NET first time experience
  DOTNET_CLI_TELEMETRY_OPTOUT: true       # Disable sending .NET CLI telemetry

jobs:
# MAUI Android Build
  build-android-ios:
    runs-on: macos-13
    name: Android and iOS Build
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET 7
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.x
          
      - name: Install MAUI Workload
        run: |
          dotnet nuget locals all --clear
          dotnet workload install maui --source https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet7/nuget/v3/index.json --source https://api.nuget.org/v3/index.json
          dotnet workload install android ios maui --source https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet7/nuget/v3/index.json --source https://api.nuget.org/v3/index.json

      - name: Restore Dependencies
        run: dotnet restore GoogleMapUtils.sln

      - name: Build MAUI Android
        run: dotnet build GoogleMapUtils.sln --configuration 'Release-NoSample' --no-restore

      - name: push nugets
        if: ${{ github.event.inputs.nuget_push == 'true' }}
        shell: pwsh
        run: |
          $files = dir ./* -include ("*.nupkg") -recurse
          foreach($file in $files)
          {
            write-host "Publishing $(${file}.FullName)"
            nuget push $file.FullName -ApiKey ${{ secrets.NUGET_API_KEY }} -Source https://api.nuget.org/v3/index.json -NonInteractive -Verbosity detailed
          }        

